// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aojlytjgdsvvvzipzzrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvamx5dGpnZHN2dnZ6aXB6enJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTcyOTQsImV4cCI6MjA2NTQ5MzI5NH0.KXqS0K5heTpe3HAZRbT9KrGUHPU3cZcmSSS-93fBRg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);